"""
This module interfaces to our user data.
"""


NAME = 'name'
FIRST_NAME = 'first_name'
LAST_NAME = 'last_name'
DOB = 'dob'
EMAIL = 'email'

MIN_USER_NAME_LEN = 2

users = {
    1234567890: {
        FIRST_NAME: "Emma",
        LAST_NAME: "Watson",
        DOB: "2002-11-20",
        EMAIL: "emma.watson@gmail.com"
    },
    9876543210: {
        FIRST_NAME: "Liam",
        LAST_NAME: "Hemsworth",
        DOB: "2001-08-17",
        EMAIL: "liam.hemsworth@yahoo.com"
    },
}


def get_users() -> dict:
    return users


# ID will be generated by the database
def add_user(user_id: int, first_name: str, last_name: str,
             dob: str, email: str):
    users[user_id] = {
        FIRST_NAME: first_name,
        LAST_NAME: last_name,
        DOB: dob,
        EMAIL: email
    }
    return users[user_id]
